### ISSUE TITLE
Make "search" keyword optional

### ISSUE THREAD

**Issue by sirinsidiator** [esoui/lexicon#11]
Whenever I try to use Lexicon, I end up using the wrong syntax and write `@Lexicon source <something>` instead of `@Lexicon search source <something>`. Would it be possible to make the "search" keyword optional?

**Comment by haggen** [comment]
Should work just by changing the regular expression here https://github.com/esoui/lexicon/blob/master/lexicon/search/search.go

I'll look into it this weekend.

**Comment by sirinsidiator** [comment]
Thanks. I have never worked with go, so I would probably break something if I changed it myself. :D
